# Generated by Django 5.2.4 on 2025-08-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_alter_project_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigments',
            name='state',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
