# Generated by Django 5.2.4 on 2025-08-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_alter_assigments_state_alter_project_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigments',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
