# Generated by Django 5.2.4 on 2025-08-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_alter_employee_project_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='project_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
